services:
  hangman-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - DB_HOST=mariadb_hangman
      - DB_PORT=3306
      - DB_USER=hangman_user
      - DB_PASSWORD=hangman_pass
      - DB_NAME=hangman_db
    depends_on:
      - mariadb_hangman
    networks:
      - proyecto

  mariadb_hangman:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: hangman_db
      MYSQL_USER: hangman_user
      MYSQL_PASSWORD: hangman_pass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - proyecto

volumes:
  mariadb_data:

networks:
  proyecto:
    name: proyecto