events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 8080;
        server_name grupo3.ifigueroap.cl;

        # Esto permite que Certbot valide tu dominio
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Redirección temporal mientras no hay SSL
        location / {
            return 200 "Servidor listo para generar certificados SSL";
            add_header Content-Type text/plain;
        }
    }
}